environment:
  nodejs_version: "18" # самая последняя стабильная версия

branches: # какие ветки отслеживаются
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование, чтобы node_modules работал быстрее

install:
  - yarn install  # команда установки зависимостей

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint # скрипт тестирования
